<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NBFORB-SE08" failures="2" tests="3" name="Surefire test" time="9.052" errors="0" timestamp="2025-04-11T11:51:25 WIB">
  <testcase classname="tests.LoginTest" name="testValidLogin" time="0.519">
    <failure type="java.lang.AssertionError" message="expected [Just a moment...] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [nopCommerce demo store. Login]
at tests.LoginTest.testValidLogin(LoginTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="tests.LoginTest" name="testValidLogin" time="0.42">
    <failure type="java.lang.AssertionError" message="expected [Just a moment...] but found [nopCommerce demo store. Login]">
      <![CDATA[java.lang.AssertionError: expected [Just a moment...] but found [nopCommerce demo store. Login]
at tests.LoginTest.testValidLogin(LoginTest.java:62)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="tests.LoginTest" name="testValidLogin" time="0.66"/>
</testsuite> <!-- Surefire test -->
